### ISSUE TITLE
Assignment-1 Factorial

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-51bit23#2]
I dont know about what do you mean by factorial? can any body help me to explain it.

**Comment by 49bit23** [comment]
its very simple. factorial means multiply number from 1 till given iuputted number.

**Comment by 51bit23** [comment]
ok..but i am still confuse. i dont undertand what you say

**Comment by 61bit23** [comment]
@51bit23 ...it means for example. you want to find factorial of 5.

Then 5!=1*2*3*4*5

**Comment by 51bit23** [comment]
5!=12345?

**Comment by 61bit23** [comment]
i means 5!= 1 multiply 2 multiply 3 multiply 4 multiply 5

**Comment by 49bit23** [comment]
exactly what i mean.

**Comment by 61bit23** [comment]
if you understand then tell me what is factorial of 3

**Comment by 51bit23** [comment]
3!=1 mul 2 mul 3

**Comment by 49bit23** [comment]
well done...you got the idea.

**Comment by 49bit23** [comment]
what is ! ? what is the meaning of this symbol

**Comment by 61bit23** [comment]
it is symbol of factorial

**Comment by 61bit23** [comment]
thank you @61bit23 and @49bit23 for help me.
