### ISSUE TITLE
assignment 4 String Reversing

### ISSUE THREAD

**Issue by 59bit23** [vtcbca/basic-programming-51bit23#3]
I don't have any idea about the string. can anyone tell me about string?

**Comment by 51bit23** [comment]
A string is a sequence of characters, such as letters, numbers, or symbols, arranged in a specific order. It's used in programming to represent text. 

For example:
- "Hello" is a string.

**Comment by 59bit23** [comment]
Ok How do I initialize a string in python?

**Comment by 51bit23** [comment]
In Python, you can initialize a string by simply assigning text (characters) to a variable using either single quotes (`' '`) or double quotes (`" "`). Both are fine.

**Comment by 59bit23** [comment]
Can we put all alphanumeric value in string?

**Comment by 51bit23** [comment]
Yes, you can put all alphanumeric values (letters and numbers) in a string in Python. A string can contain any combination of letters (like `A`, `b`, `z`), numbers (like `1`, `2`, `9`), and even special characters (like `@`, `#`, `$`).

For example:


my_string = "abc123XYZ@#"

**Comment by 59bit23** [comment]
Which function is used for reversing the string?

**Comment by 51bit23** [comment]
In Python, you can reverse a string using slicing. There is no built-in function specifically for reversing, but slicing allows you to easily reverse the string.

```
Here’s how you can do it:

my_string = "Hello"
reversed_string = my_string[::-1]
print(reversed_string)  
# Output: "olleH"
```

**Comment by 59bit23** [comment]
Thank you @51bit23 for your co-operation.
