### ISSUE TITLE
Assignment-2:  Prime Number Checker

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-51bit23#4]
can someone tell me how can i make this program in python?

**Comment by 48bit23** [comment]
To make a Prime Number Checker in Python, use a function to check if a number is divisible by any number from 2 to \( \sqrt{n} \). Take user input, validate it, and print if the number is prime or not.

**Comment by 51bit23** [comment]
What happens if i input a negative number?

**Comment by 48bit23** [comment]
Negative numbers are not prime, so the program should output: "Not a Prime Number."

**Comment by 51bit23** [comment]
Can 1 be a prime number?

**Comment by 48bit23** [comment]
No, 1 is not prime because it has only one divisor (itself).

**Comment by 51bit23** [comment]
Why is 2 considered a prime number?

**Comment by 48bit23** [comment]
2 is prime because it is divisible only by 1 and itself, making it the smallest prime number.

**Comment by 51bit23** [comment]
an we use a while loop instead of a for loop?

**Comment by 48bit23** [comment]
Yes, a while loop can also be used to check divisors.

**Comment by 51bit23** [comment]
How do you find all prime numbers up to a given number?

**Comment by 48bit23** [comment]
Use a loop to check each number in the range and store primes in a list.

**Comment by 51bit23** [comment]
ok got it.
