### ISSUE TITLE
Assignment-3 : Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-51bit23#5]
how a Fibonacci Sequence Generator work in python.

**Comment by 64bit23** [comment]
A Fibonacci Sequence Generator in Python starts with 0 and 1, then calculates each new term by adding the last two terms. This process continues in a loop until it reaches the desired number of terms or a maximum value.

**Comment by 51bit23** [comment]
What is the Fibonacci sequence?

**Comment by 64bit23** [comment]
The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting with 0 and 1.

**Comment by 51bit23** [comment]
What are the first five terms of the Fibonacci sequence?

**Comment by 64bit23** [comment]
The first five terms are: 0, 1, 1, 2, 3.

**Comment by 51bit23** [comment]
How can you calculate Fibonacci numbers in Python?

**Comment by 64bit23** [comment]
Use a loop to add the last two numbers repeatedly or a recursive function.

**Comment by 51bit23** [comment]
What happens if the user enters a negative number?

**Comment by 64bit23** [comment]
The program should handle this case by printing: "Invalid input. Please enter a positive number."

**Comment by 51bit23** [comment]
Okey thats right thank you. @64bit23 /
